#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $OWGW_DB_USER WITH ENCRYPTED PASSWORD '$OWGW_DB_PASSWORD';
    CREATE DATABASE $OWGW_DB OWNER $OWGW_DB_USER;
    CREATE USER $OWSEC_DB_USER WITH ENCRYPTED PASSWORD '$OWSEC_DB_PASSWORD';
    CREATE DATABASE $OWSEC_DB OWNER $OWSEC_DB_USER;
    CREATE USER $OWFMS_DB_USER WITH ENCRYPTED PASSWORD '$OWFMS_DB_PASSWORD';
    CREATE DATABASE $OWFMS_DB OWNER $OWFMS_DB_USER;
    CREATE USER $OWPROV_DB_USER WITH ENCRYPTED PASSWORD '$OWPROV_DB_PASSWORD';
    CREATE DATABASE $OWPROV_DB OWNER $OWPROV_DB_USER;
EOSQL
