http:
  services:
    ucentralgw-ui:
      loadBalancer:
        servers:
          - url: "http://ucentralgw-ui.wlan.local:80/"

  routers:
    ucentralgw-ui:
      entryPoints: "ucentralgwui"
      service: "ucentralgw-ui"
      rule: "PathPrefix(`/`)"

tcp:
  services:
    ucentralgw-websocket:
      loadBalancer:
        servers:
          - address: "ucentralgw.wlan.local:15002"
    ucentralgw-restapi:
      loadBalancer:
        servers:
          - address: "ucentralgw.wlan.local:16002"
    ucentralgw-fileupload:
      loadBalancer:
        servers:
          - address: "ucentralgw.wlan.local:16003"
    ucentralsec-restapi:
      loadBalancer:
        servers:
          - address: "ucentralsec.wlan.local:16001"
    ucentralfms-restapi:
      loadBalancer:
        servers:
          - address: "ucentralfms.wlan.local:16004"
    rttys:
      loadBalancer:
        servers:
          - address: "rttys.wlan.local:5913"

  routers:
    ucentralgw-websocket:
      entryPoints: "ucentralgwwebsocket"
      service: "ucentralgw-websocket"
      rule: "HostSNI(`*`)"
      tls:
        passthrough: true
    ucentralgw-restapi:
      entryPoints: "ucentralgwrestapi"
      service: "ucentralgw-restapi"
      rule: "HostSNI(`*`)"
      tls:
        passthrough: true
    ucentralgw-fileupload:
      entryPoints: "ucentralgwfileupload"
      service: "ucentralgw-fileupload"
      rule: "HostSNI(`*`)"
      tls:
        passthrough: true
    ucentralsec-restapi:
      entryPoints: "ucentralsecrestapi"
      service: "ucentralsec-restapi"
      rule: "HostSNI(`*`)"
      tls:
        passthrough: true
    ucentralfms-restapi:
      entryPoints: "ucentralfmsrestapi"
      service: "ucentralfms-restapi"
      rule: "HostSNI(`*`)"
      tls:
        passthrough: true
    rttys:
      entryPoints: "rttys"
      service: "rttys"
      rule: "HostSNI(`*`)"
      tls:
        passthrough: true
