# This helm values file is to be used when OWLS is run externally.
owgw:
  services:
    owgw:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "16102"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:289708231103:certificate/2cc8c764-11fd-411d-bf7d-a93f488f3f6c
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "16002,16003,17002"

  configProperties:
    # done by default for owgw now:
    #simulatorid: 53494D020202
    # on a host with more CPUs you may need to bump this up from default of 64
    storage.type.postgresql.maxsessions: 120
    # this actually disables websocket logging:
    logging.websocket: true
    # consider lowering the # of days to keep archives in the database
    #archiver.db.0.name = healthchecks
    #archiver.db.0.keep = 1
    #archiver.db.1.name = statistics
    #archiver.db.1.keep = 1
    #archiver.db.2.name = devicelogs
    #archiver.db.2.keep = 1
    #archiver.db.3.name = commandlist
    #archiver.db.3.keep = 1

  resources:
    requests:
      cpu: 2000m
      memory: 3Gi
    limits:
      cpu: 2000m
      memory: 5Gi

# Postgres tuning for larger # of APs
#postgresql:
#  primary:
#    resourcesPreset: large
#    persistence:
#      size: 120Gi

owprov:
  # consider providing more memory to owprov
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 4Gi
